# Dev environment properties
# Used when mule.env=dev

# HTTP Listener
http.listener.host=0.0.0.0
http.listener.port=8081

# DummyJSON upstream service
dummyjson.host=dummyjson.com
dummyjson.port=443
